github: [devinschumacher]
open_collective: devinschumacher
custom: [
  "https://apps.serp.co/porntrex-downloader",
  "https://serp.co/products/porntrex-downloader/reviews/",
  "https://extensions.serp.co/porntrex-downloader",
  "https://browserextensions.io/porntrex-downloader"
]
